language: csharp
solution:  ./src/Senparc.CO2NET.sln

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 2.2.101
 #   - os: osx # OSX 10.11
 #     osx_image: xcode7.2
 #     dotnet: 2.1.300
 #   - os: osx # OSX 10.12
 #     osx_image: xcode7.3
 #     dotnet: 2.1.300

install:
#  - dotnet restore
  - nuget restore ./src/Senparc.CO2NET.sln
  - nuget install Newtonsoft.Json -Version 12.0.1

script:
  - dotnet --info
  - cd ./src/
  - dotnet build
  # Run a new console app
  #- x#build /p:Configuration=Release ./src/Senparc.CO2NET.sln

#language: csharp

#solution:  ./src/Senparc.CO2NET.sln
#scripts:
#  - xbuild /p:Configuration=Release ./src/Senparc.CO2NET.sln
  
#install:
# - nuget install Newtonsoft.Json -Version 11.0.2
# - nuget restore ./src/Senparc.CO2NET.sln
